@startuml
skinparam actorStyle awesome
actor User
participant "Bingo Board" as BB
participant "Controller" as CR
participant "Database" as DB


== 게임 시작 ==

CR -> DB : 프로게이머 관련 데이터 요청
DB -> CR : 프로게이머 데이터 반환
CR -> BB : 빙고 보드에 프로게이머 힌트 제공
BB -> User : 빙고 보드 출력 및 힌트 표시
CR -> DB : 일정 갯수 만큼 프로게이머의 정보 요청
DB -> CR : 프로게이머 정보 반환

== 빙고 보드 칸 선택 ==

loop 횟수 만큼

    CR -> User : 순차적으로 프로게이머 제시
    User -> BB : 칸 클릭
    BB -> CR : 해당 칸 클릭 알림
    CR -> CR : 정답인지 확인
    alt 선택한 칸이 정답일 경우
        CR -> BB : 정답 알림
        BB -> User : 칸 초록색으로 표시
    else 선택한 칸이 오답일 경우
        CR -> BB : 오답 알림
        BB -> User : 칸 빨간색으로 일시적 표시
    end
end

== 최대 시도 횟수 초과시 ==
alt 시도 횟수 초과
    CR -> User : 실패 알림 및 실패 화면 출력
end

== 빙고 성공 시 ==
alt 빙고 성공
    CR -> User : 성공 알림 및 성공 화면 출력
end

@enduml
