@startuml
skinparam actorStyle awesome
actor User
participant "Input Form" as IF
participant "Quiz Screen" as QS
participant "Controller" as CR
participant "Database" as DB

== Initial Screen ==
CR -> DB : 팀 로스터 및 대회 성적 데이터 요청
DB -> CR : 팀 로스터 및 대회 성적 데이터 반환

== 팀 맞추기 퀴즈 ==
loop 총 5개의 팀, 각 3번의 기회 (총 15회)
    CR -> QS : 순차적으로 로스터 및 대회 성적 반환

    ==사용자가 팀 입력 도중==
    User -> IF : 팀 입력
    IF -> CR : 입력 값 전달
    CR -> DB : 입력 값을 포함하는 팀 리스트 요청
    DB -> CR : 팀 리스트 반환
    CR -> IF : 팀 리스트 제공
    IF -> User : 팀 리스트 출력

    ==사용자가 팀 입력==
    User -> IF : 팀 입력
    IF -> CR : 입력 값 전달
    CR -> DB : 입력 값과 일치하는 팀 요청
    DB -> CR : 일치하는 팀 반환
    CR -> IF : 일치하는 팀 제공
    IF -> User : 일치하는 팀 출력
    User -> IF : Enter or 리스트 클릭
    IF -> CR : 사용자가 답 입력 알림
    CR -> DB : 입력 값 정보 요청
    DB -> CR : 팀 정보 반환

    alt 정답인 경우
        CR -> QS : 팀 로고 및 이름 표시, BG 초록색으로 표시
        CR -> User : 정답 알림 및 다음 팀으로 이동
    else 오답인 경우
        CR -> QS : BG 빨간색으로 일시적 표시
        CR -> User : 오답 알림
    end
end

== 퀴즈 종료 시 ==
CR -> User : 결과 화면 출력 (맞춘 팀의 개수 / 총 팀 개수 AND 사용한 기회 / 총 기회)

@enduml
