@startuml
skinparam actorStyle awesome
actor User
participant "Input Form" as IF
participant "Bingo Board" as BB
participant "Controller" as CR
participant "Database" as DB


== 게임 시작 ==
CR -> DB : 행과 열 힌트에 사용할 정보 요청
DB -> CR : 정보 제공
CR -> BB : 행과 열 힌트 제공
BB -> User : 빙고 보드 출력

== 정해진 횟수 내에 맞추기 ==
loop 최대 횟수(예: 15회)

    ==사용자가 프로게이머 입력 도중==
    User -> IF : ID 또는 Name 입력
    IF -> CR : 입력 값 전달
    CR -> DB : 입력 값을 포함하는 ID/Name 리스트 요청
    DB -> CR : ID/Name 리스트 반환
    CR -> IF : ID/Name 리스트 제공
    IF -> User : ID/Name 리스트 출력

    ==사용자가 프로게이머 입력==
    User -> IF : ID 또는 Name 입력
    IF -> CR : 입력 값 전달
    CR -> DB : 입력 값과 일치하는 ID/Name 요청
    DB -> CR : 일치하는 ID/Name 반환
    CR -> IF : 일치하는 ID/Name 제공
    IF -> User : 일치하는 ID/Name 출력
    User -> IF : Enter or 리스트 클릭
    IF -> CR : 사용자가 답 입력 알림
    CR -> DB : 입력 값 정보 요청
    DB -> CR : Progamer 정보 반환
    alt 정답인 경우
        CR -> User : 정답 알림
        CR -> BB : 칸 초록색으로 표시 및 프로게이머 얼굴 표시

    else 오답인 경우
        CR -> User : 오답 알림
        CR -> BB : 칸 일시적 빨간색으로 표시
    end
end

== 최대 시도 횟수 초과시 ==
alt 시도 횟수 초과
    CR -> User : 실패 알림 및 실패 화면 출력
end

@enduml
