@startuml
skinparam actorStyle awesome
actor User
participant "Input Form" as IF
participant "Controller" as CR
participant "Database" as DB

==사용자가 프로게이머 입력 도중==
User -> IF : ID 또는 Name 입력
IF -> CR : 입력 값 전달
CR -> DB : 입력 값을 포함하는 ID/Name 리스트 요청
DB -> CR : ID/Name 리스트 반환
CR -> IF : ID/Name 리스트 제공
IF -> User : ID/Name 리스트 출력


==사용자가 프로게이머 입력==
User -> IF : ID 또는 Name 입력
IF -> CR : 입력 값 전달
CR -> DB : 입력 값과 일치하는 ID/Name 요청
DB -> CR : 일치하는 ID/Name 반환
CR -> IF : 일치하는 ID/Name 제공
IF -> User : 일치하는 ID/Name 출력
User -> IF : Enter or 리스트 클릭
IF -> CR : 사용자가 답 입력 알림
CR -> DB : 입력 값 정보 요청
DB -> CR : Progamer 정보 반환
alt 정답 일 경우
    CR -> User : 블러 처리된 이미지 해제 및 초록색 배경 표시

else 오답 일 경우
    CR -> User : 힌트 출력
end



==횟수 8회 초과==
    CR -> User : 실패 알림 및 블러 처리된 이미지 해제, 빨간색 배경 표시

@enduml
