spring:
  application:
    name: ProgamerQuiz

  datasource:
    url: jdbc:mysql://localhost:3306/progamerquiz-mysql?rewriteBatchedStatements=true
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  show-login-endpoint: true
  api-docs:
    path: /v3/api-docs


# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
server:
  tomcat:
    mbeanregistry:
      enabled: true
  # Session
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: false # 개발 환경에서는 false, 프로덕션에서는 true
        same-site: strict