@startuml
skinparam actorStyle awesome
actor User
actor Program

Database ProgamerDB
Database TeamDB

rectangle Quiz1 {
    rectangle Input1
    User -left-> Quiz1User
    Quiz1User --> Input1 : Typing Progamer ID or Name
    Input1 -> Program : Search ProgamerDB
    Program --> ProgamerDB : Request Progamer List
    ProgamerDB --> Program : Send Progamer List
    Program --> Quiz1User : Suggestion Progamer List
    Quiz1User --> Input1 : Select Progamer
    Input1 --> Program : Request whether correct
}

rectangle Quiz2 {
    rectangle Input2
    User -right-> Quiz2User
    Quiz2User --> Input2 : Typing Team
    Input2 -> Program : Search TeamDB
    Program --> TeamDB : Request Team List
    TeamDB --> Program : Send Team List
    Program --> Quiz2User : Suggestion Team List
    Quiz2User --> Input2 : Select Team
    Input2 --> Program : Request whether correct
}


rectangle Quiz3 {
    User --> Quiz3User
    Quiz3User --> Board : Select Board
    Board --> Program : Request whether correct
}

@enduml