@startuml
skinparam actorStyle awesome
actor User
actor Program

rectangle MainPage {
  User --> (Select Quiz)
  (Select Quiz) --> Program
  Program --> (Move to Quiz)
  (Move to Quiz) --> Quiz
}


rectangle Quiz {
  User --> (Search\nProgamer)
  (Search\nProgamer) --> Program
  Program --> (Suggestion\nProgamer list)
  (Suggestion\nProgamer list) --> User
  User --> (Select\nProgamer)
}

@enduml
